Use mimetypes for the detection of files in form-data
Http-Multipart-Data-Parser/Http-Multipart-Data-Parser pull request #89
Opened 2020-11-30 12:05 UTC by bkrbtc

RFC 7578 defines the "filename" parameter as "SHOULD". This means the existence of the parameter is not a sufficient criteria to distinguish between files and parameters. I added an option to detectet files by it's mimetype. This list can be enhanced by the user of the library

2020-11-30 14:39 UTC, Jericho commented
Thank you for submitting this PR. Do you mind raising an issue to discuss the underlying problem you are trying to solve? Please include as much info as you can such as repro steps, describe the circumstances where you experience this problem etc.

2020-11-30 15:31 UTC, bkrbtc commented
https://github.com/Http-Multipart-Data-Parser/Http-Multipart-Data-Parser/issues/90

2020-11-30 19:46 UTC, Jericho requested changes
Also I get a few warnings in Visual Studio such as:
- SA1001 Commas should be followed by whitespace.
- SA1013 Closing brace should be preceded by a space.
- SA1629 Documentation text should end with a period

I'll se I can push changes to your PR to fix those.

2020-11-30 19:46 UTC, Jericho commented on Source/HttpMultipartParser/MultipartFormDataParser.cs
> +            return MultipartFormDataParser.Parse(stream, null, encoding, binaryBufferSize, null);
you forgot to pass `boundary` when invoking `MultipartFormDataParser.Parse`.

```suggestion
            return MultipartFormDataParser.Parse(stream, boundary, encoding, binaryBufferSize, null);
```

2020-12-01 08:06 UTC, bkrbtc commented on Source/HttpMultipartParser/MultipartFormDataParser.cs
> +            return MultipartFormDataParser.Parse(stream, null, encoding, binaryBufferSize, null);
Sry for that. Was under high time pressure yesterday. Needed this fix for an important project and started the pull request a bit early.

2020-12-01 14:40 UTC, Jericho approved these changes
Looks good to me!

2020-12-01 14:52 UTC, bkrbtc commented
> Looks good to me!

For me too. If you like to merge feel free. Thank you for your support.

2020-12-01 15:48 UTC, merged

2020-12-03 19:21 UTC, Jericho commented
I got busy with other projects in the last few days but I have some time now. Will look at releasing today or tomorrow.

2020-12-04 09:01 UTC, bkrbtc commented
No Problem. Thanks